server:
  port: 8096
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.27.212:3306/guli_oms
    username: root
    password: root
  rabbitmq:
    host: 192.168.27.212
    username: root
    password: root
    virtual-host: /root
  redis:
    host: 192.168.27.212:6379
  #nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.27.1:8848
mybatis-plus:
  mapper-locations: classpath:mapper/oms/**/*.xml
  global-config:
    db-config:
      id-type: auto
  rabbitmq:
    host: 192.168.27.212
    virtual-host: /root
    username: root
    password: root

auth:
  jwt:
    publicKeyPath: E:\\JavaEESoftware\\GmallNew\\gmall-jwt-key\\rsa.pub
    cookieName: GMALL_TOKEN