server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
auth:
  jwt:
    privateKeyPath: E:\\JavaEESoftware\\GmallNew\\gmall-jwt-key\\rsa.pri
    publicKeyPath: E:\\JavaEESoftware\\GmallNew\\gmall-jwt-key\\rsa.pub
    secret: alkshdfkashdfk@#&^%(&(*()sdalkfjla;ksjd\[;][;]
    cookieName: GMALL_TOKEN
    exprieTime: 180