server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.27.212
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.27.212:3306/guli_ums
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  global-config:
    db-config:
      id-type: auto